site_name: AMD GPU Operator
nav:
  - Home: index.md
  - Getting Started:
    - Overview: overview.md
  - User Guide:
    - Install Operator:
        - Kubernetes (Helm): installation/kubernetes-helm.md
        - OpenShift (Helm): installation/openshift-helm.md
        - OpenShift (OLM): installation/openshift-olm.md  
    - Install Custom Resource:
      - Installation: drivers/installation.md
      - Using Pre-Compiled Driver Image: drivers/precompiled-driver.md
      - Secure Boot: drivers/secure-boot.md
    - Upgrades:
      - Driver Upgrade: drivers/upgrading.md
      - Kernel Upgrade: upgrades/kernel.md
    - Metrics:
      - Exporter: metrics/exporter.md
      - Kube Rbac Proxy: metrics/kube-rbac-proxy.md
    - Usage: usage.md
    - Uninstallation: uninstallation/uninstallation.md
    - Troubleshooting: troubleshooting.md      
  - Specialized Networks:
    - HTTP Proxy: specialized_networks/http-proxy.md
    - Air-Gapped Installation: specialized_networks/airgapped-install.md
  - Contributing:
    - Developer Guide: contributing/developer-guide.md
    - Documentation Standards: contributing/documentation-standards.md

theme: 
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - dockerfile
    - shell
    - yaml

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ROCm/gpu-operator
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/rocm/gpu-operator

repo_url: https://github.com/ROCm/gpu-operator
edit_uri: blob/main/docs/docs/
copyright: Copyright © 2024-2025, Advanced Micro Devices, Inc.
